name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Collect JARs
        run: |
          mkdir all-jars
          for module in $(ls -d */); do
            module=${module%/}
            cd $module
            for f in */; do
              echo "$f"
            done
            cd ..
            echo "${module}build/libs/*.jar"
            if [ -d "${module}build/libs" ]; then
             cp "${module}build/libs/*.jar" all-jars/
            else
              echo "nie ma $module"
            fi
          done
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: all-jars
          path: all-jars

  security:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-sub-projects